# Generated by Django 4.1.7 on 2023-04-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creado_el',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modificado_el',
        ),
    ]
